# Drop stored procedures
-- Groups
DROP PROCEDURE IF EXISTS getGroups; 
DROP PROCEDURE IF EXISTS addGroups;
DROP PROCEDURE IF EXISTS deleteGroups;
DROP PROCEDURE IF EXISTS updateGroups;
-- Leaders
DROP PROCEDURE IF EXISTS deleteLeaders;
DROP PROCEDURE IF EXISTS addLeaders;
DROP PROCEDURE IF EXISTS getLeaders;
DROP PROCEDURE IF EXISTS updateLeaders;
-- Scouts
DROP PROCEDURE IF EXISTS getScouts;
DROP PROCEDURE IF EXISTS addScouts;
DROP PROCEDURE IF EXISTS deleteScouts; 
DROP PROCEDURE IF EXISTS updateScouts;


